### ISSUE TITLE
issue of GRO2LAM: invalid literal for int() with base 10:

### ISSUE THREAD

**Issue by singlebook** [hernanchavezthielemann/GRO2LAM#30]
I am using GRO2LAM to convert Gromacs input files to Lammps input files. However, I am getting this error:

Warning!! -- There are inconsistencies in your input files
invalid literal for int() with base 10: '3.766'

It converts a non-integer value as a string into an integer by using function int().
[issue.tar.gz](https://github.com/hernanchavezthielemann/GRO2LAM/files/4590396/issue.tar.gz)

**Comment by hernanchavezthielemann** [comment]
Hi,
Thanks for submitting this issue.
I found some interesting things:

### First:
there is a dihedral definition making this error
SI   OS    1     0.000 3.766      3
 SI   OH   1     0.000 3.766      3

Adding the oplsaa wildcard symbol solves that problem, by changing those lines to:
X SI  OS  X   1    0.000 3.766      3
X  SI   OH  X  1     0.000 3.766      3

- However, this should be handled in a more explanatory way.

### Second:
As you can see in the examples folder the protein used to be in the top file. Therefore, doing that it comes out the converted file.

- So, to solve this, it should be implemented opls recognition outside the top file.

### Third:
I've noticed that since there are too many groups in the protein, the restraint option cannot show all the possibilities.

- A nice fix for this could be a y-scroll bar, fixing the maximum window size.

I would say that all of them are enhancement. Nevertheless, number two could be a bug too.

**Comment by hernanchavezthielemann** [comment]
Hi Wei @singlebook 

I think that with the last version this is solved.
If you agree I'm going to close this.

Best,
Hernan
